server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.84.129
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.84.129
ly:
  sms:
    accessKeyId: L # 你自己的accessKeyId
    accessKeySecret: p # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_209195011 # 模板名称